### ISSUE TITLE
`in` operator ArgumentError

### ISSUE THREAD

**Issue by elliotdes** [cerbos/query-plan-adapters#6]
This is on Cerbos 0.20.0

Looking at a snippet of my query plan:
```yml
{
            "expression": {
              "operator": "in",
              "operands": [
                {
                  "value": "random_value"
                },
                {
                  "variable": "request.resource.attr.tags"
                }
              ]
            }
```
and then we look at the get_query function defined in `cerbos_sqlalchemy`:
```python
        if operator == "in":
            return column.in_(value)
```
I get the following error:
```
sqlalchemy.exc.ArgumentError: IN expression list, SELECT construct, or bound parameter object expected, got 'random_value'.
```
If `value` is not a list, should the code in `cerbos_sqlalchemy` be the following instead?:

```python
        if operator == "in":
            return column.in_([value])
```

The [sqlalchemy docs](https://docs.sqlalchemy.org/en/14/core/operators.html) say:

> IN is available most typically by passing a **list** of values to the [ColumnOperators.in_()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.in_) method:

Making these changes locally fixes the issue for me.

**Comment by elliotdes** [comment]
https://github.com/cerbos/query-plan-adapters/blob/21de38586a17da0df8cd593d8867804e463d9c44/sqlalchemy/tests/test_query.py#L290

Seems like the tests only covers cases where `value` is a list

**Comment by Sambigeara** [comment]
Oo, thanks for raising. Will draw up a fix
